### PR TITLE
Xcode support

### PR DESCRIPTION
**Pull request by slavikus**
Adding Xcode project to allow compilation/debugging on macOS. :)

### CODE REVIEW

**Comment by msuiche** [comment]
VMState.cpp:671 versus VMState.cpp:736

**Comment by slavikus** [comment]
Matt, I don't get it, what's about VMState.cpp:671 vs VMState.cpp:736? :)

**Comment by johndpope** [comment]
In your pull request / (view all files) there's changes to those files that's not clear what it's doing or why it's needed. Perhaps cherry pick Xcode stuff and discard those changes.

**Comment by slavikus** [comment]
Oh. Of course I could exclude these things, but in my opinion they don't do much harm as it silences the (proper) warnings from the compiler about not all case values being handled in a switch. Let me know if it's inappropriate.

**Pull request merged**
